name: tessafold_task
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  awesome_dialog: ^3.2.1
  bloc_concurrency: ^0.2.5
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  dot_navigation_bar: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_svg_icons: ^0.0.1+4
  get_it: ^8.0.3
  go_router: ^14.8.1
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/lang/
    - assets/images/
    - assets/icons/
    - assets/svg/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-VariableFont_slnt,wght.ttf
